__title__ = 'CellDetection'
__version__ = '0.4.3'
__author__ = 'Eric Upschulte'
__email__ = 'e.upschulte@fz-juelich.de'
__license__ = 'Apache License, Version 2.0'
__summary__ = 'Cell Detection with PyTorch.'
__url__ = __uri__ = 'https://celldetection.org'
