# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 19 * * *'  # Runs daily at 19:30 UTC
  workflow_dispatch:      # Allows the workflow to be triggered manually from the GitHub UI

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 60  # Number of days of inactivity before an issue or PR is marked stale
        days-before-close: 7   # Number of days to close the issue/PR after it has been marked as stale
        exempt-issue-labels: 'pinned, security'  # Labels which exempt an issue from being marked as stale
        exempt-pr-labels: 'pinned, security'     # Labels which exempt a PR from being marked as stale
        operations-per-run: 30                  # Limit the number of operations per run
        remove-stale-when-updated: true          # Remove stale label when new activity occurs
        debug-only: true                        # Set to false to perform actions, true to only log them
